<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Qasedak.Modules.Identity.Domain\Qasedak.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Qasedak.BuildingBlocks.Application\Qasedak.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
