// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qasedak.Modules.Automations.Infrastructure.Persistence;

#nullable disable

namespace Qasedak.Modules.Automations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutomationsDbContext))]
    [Migration("20260905000458_AddChannelAccountBinding")]
    partial class AddChannelAccountBinding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("automations")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qasedak.Modules.Automations.Infrastructure.Persistence.AutomationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChannelAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CurrentVersionFrozen")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "ChannelAccountId");

                    b.HasIndex("WorkspaceId", "CreatedAtUtc");

                    b.ToTable("automations", "automations");
                });

            modelBuilder.Entity("Qasedak.Modules.Automations.Infrastructure.Persistence.AutomationRunActionRow", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActionIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AutomationRunRowId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("RunId", "ActionIndex");

                    b.HasIndex("AutomationRunRowId");

                    b.ToTable("automation_run_actions", "automations");
                });

            modelBuilder.Entity("Qasedak.Modules.Automations.Infrastructure.Persistence.AutomationRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutomationId")
                        .HasColumnType("uuid");

                    b.Property<int>("AutomationVersionNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TriggerEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AutomationId", "TriggerEventId")
                        .IsUnique();

                    b.ToTable("automation_runs", "automations");
                });

            modelBuilder.Entity("Qasedak.Modules.Automations.Infrastructure.Persistence.AutomationVersionRow", b =>
                {
                    b.Property<Guid>("AutomationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition_json");

                    b.HasKey("AutomationId", "Number");

                    b.HasIndex("AutomationId");

                    b.ToTable("automation_versions", "automations");
                });

            modelBuilder.Entity("Qasedak.Modules.Automations.Infrastructure.Persistence.AutomationRunActionRow", b =>
                {
                    b.HasOne("Qasedak.Modules.Automations.Infrastructure.Persistence.AutomationRunRow", null)
                        .WithMany("Actions")
                        .HasForeignKey("AutomationRunRowId");
                });

            modelBuilder.Entity("Qasedak.Modules.Automations.Infrastructure.Persistence.AutomationVersionRow", b =>
                {
                    b.HasOne("Qasedak.Modules.Automations.Infrastructure.Persistence.AutomationRow", null)
                        .WithMany("Versions")
                        .HasForeignKey("AutomationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qasedak.Modules.Automations.Infrastructure.Persistence.AutomationRow", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Qasedak.Modules.Automations.Infrastructure.Persistence.AutomationRunRow", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
