/*
 * Application-owned API client for workspace Instagram connections
 * (GET/POST/DELETE /api/v1/workspaces/{id}/instagram/*). Never regenerated by design sync.
 */
import { request } from "./http";
import type { ConnectionState } from "../../features/instagram/health";

export interface ConnectionsApi {
  list(token: string, workspaceId: string, includeDisconnected?: boolean): Promise<{ items: ConnectionState[] }>;
  authorizeUrl(token: string, workspaceId: string, redirectUri: string): Promise<{ url: string; state?: string }>;
  connect(
    token: string,
    workspaceId: string,
    body: { authorizationCode: string; redirectUri: string },
  ): Promise<{ accountId: string }>;
  disconnect(token: string, workspaceId: string, accountId: string): Promise<void>;
}

export function connectionsApi(): ConnectionsApi {
  const base = (workspaceId: string) => `/api/v1/workspaces/${workspaceId}/instagram`;
  return {
    list: (token, workspaceId, includeDisconnected = false) =>
      request(`${base(workspaceId)}/connections?includeDisconnected=${includeDisconnected}`, { bearerToken: token }),
    authorizeUrl: (token, workspaceId, redirectUri) => {
      const q = `redirectUri=${encodeURIComponent(redirectUri)}`;
      return request(`${base(workspaceId)}/authorize-url?${q}`, { bearerToken: token });
    },
    connect: (token, workspaceId, body) =>
      request(`${base(workspaceId)}/connections`, { method: "POST", body, bearerToken: token }),
    disconnect: async (token, workspaceId, accountId) => {
      await request(`${base(workspaceId)}/connections/${accountId}`, { method: "DELETE", bearerToken: token });
    },
  };
}
