/*
 * Application-owned API client for the workspace contact CRM
 * (GET /contacts/by-identity, POST/DELETE /contacts/{id}/tags[/{tag}], POST /contacts/{id}/notes).
 * Never regenerated by design sync. The inbox resolves a conversation's participant to its
 * contact via GET /contacts/by-identity and surfaces the CRM panel behind these endpoints.
 */
import { ApiError, request } from "./http";

export interface ContactIdentity {
  channel: string;
  providerIdentity: string;
}

export interface ContactNote {
  id: string;
  body: string;
  createdAtUtc: string;
}

export interface ContactDetail {
  id: string;
  displayName: string;
  status: string;
  createdAtUtc: string;
  lastSeenAtUtc: string;
  interactionCount: number;
  mergedIntoId: string | null;
  identities: ContactIdentity[];
  tags: string[];
  notes: ContactNote[];
}

export interface ContactsApi {
  /** Resolves the contact bound to a provider identity; null when none exists yet. */
  getByIdentity(
    token: string,
    workspaceId: string,
    channel: string,
    providerIdentity: string,
  ): Promise<ContactDetail | null>;
  addTag(token: string, workspaceId: string, contactId: string, tag: string): Promise<void>;
  removeTag(token: string, workspaceId: string, contactId: string, tag: string): Promise<void>;
  addNote(token: string, workspaceId: string, contactId: string, body: string): Promise<{ noteId: string }>;
}

export function contactsApi(): ContactsApi {
  const base = (workspaceId: string) => `/api/v1/workspaces/${workspaceId}/contacts`;
  const encode = encodeURIComponent;

  return {
    getByIdentity: async (token, workspaceId, channel, providerIdentity) => {
      const url = `${base(workspaceId)}/by-identity?channel=${encode(channel)}&identity=${encode(providerIdentity)}`;
      try {
        return await request(url, { bearerToken: token });
      } catch (error) {
        // A conversation can precede its CRM contact (projection not yet reflected).
        if (error instanceof ApiError && error.status === 404) return null;
        throw error;
      }
    },
    addTag: async (token, workspaceId, contactId, tag) => {
      await request(`${base(workspaceId)}/${contactId}/tags`, { method: "POST", body: { tag }, bearerToken: token });
    },
    removeTag: async (token, workspaceId, contactId, tag) => {
      await request(`${base(workspaceId)}/${contactId}/tags/${encode(tag)}`, { method: "DELETE", bearerToken: token });
    },
    addNote: async (token, workspaceId, contactId, body) =>
      request(`${base(workspaceId)}/${contactId}/notes`, { method: "POST", body: { body }, bearerToken: token }),
  };
}