/*
 * Application-owned HTTP layer for the Qasedak API.
 * NOT part of the Penpot visual sync — per docs/design/PENPOT-SYNC.md this file is
 * never regenerated by design re-syncs. Server authorization remains the source of
 * truth; the browser only carries the bearer token issued by POST /identity/login.
 */
import type { IdentityApi } from "./identity";

// Browser requests stay same-origin so the immutable Web image is independent of
// the public domain. A server-side caller may use the internal URL supplied by the
// deployment, but that hostname must never be emitted into the browser bundle.
const API_BASE_URL =
  typeof window === "undefined"
    ? process.env.QASEDAK_API_INTERNAL_URL ?? process.env.NEXT_PUBLIC_API_BASE_URL ?? ""
    : "";

/** Injectable transport so unit tests can stub network behavior deterministically. */
export type FetchLike = typeof fetch;

let currentFetch: FetchLike = fetch;

/** Test seam — swap the transport; production code never calls this. */
export function setTransport(transport: FetchLike): void {
  currentFetch = transport;
}

export class ApiError extends Error {
  readonly status: number;
  /** Stable failure code emitted by the backend (e.g. "auth.weakPassword"). */
  readonly code: string | null;

  constructor(status: number, code: string | null) {
    super(code ?? `HTTP ${status}`);
    this.name = "ApiError";
    this.status = status;
    this.code = code;
  }
}

interface RequestOptions {
  method?: "GET" | "POST" | "PUT" | "DELETE";
  body?: unknown;
  bearerToken?: string | null;
}

export async function request<T>(path: string, options: RequestOptions = {}): Promise<T> {
  const headers: Record<string, string> = {};
  if (options.body !== undefined) headers["content-type"] = "application/json";
  if (options.bearerToken) headers.authorization = `Bearer ${options.bearerToken}`;

  const response = await currentFetch(`${API_BASE_URL}${path}`, {
    method: options.method ?? "GET",
    headers,
    body: options.body === undefined ? undefined : JSON.stringify(options.body),
  });

  if (!response.ok) {
    let code: string | null = null;
    try {
      const payload = (await response.json()) as { code?: string };
      code = payload?.code ?? null;
    } catch {
      code = null;
    }
    throw new ApiError(response.status, code);
  }

  if (response.status === 204) return undefined as T;
  return (await response.json()) as T;
}

export function api(): IdentityApi {
  return {
    register: (body) => request<{ userId: string }>("/api/v1/identity/register", { method: "POST", body }),
    login: async (body) => {
      const result = await request<{ accessToken: string; expiresAtUtc: string }>(
        "/api/v1/identity/login",
        { method: "POST", body },
      );
      return result;
    },
    me: (token) => request<{ userId: string; email: string }>("/api/v1/identity/me", { bearerToken: token }),
    createWorkspace: (token, body) =>
      request<{ workspaceId: string; name: string }>("/api/v1/workspaces", {
        method: "POST",
        body,
        bearerToken: token,
      }),
    listMembers: (token, workspaceId) =>
      request<{ workspaceName: string; members: { userId: string; role: string }[] }>(
        `/api/v1/workspaces/${workspaceId}/members`,
        { bearerToken: token },
      ),
  };
}

export const apiBaseUrl = API_BASE_URL;
