/*
 * Application-owned API client for the workspace Instagram analytics surface
 * (GET .../connections/{accountId}/overview and .../followers/history, M13-007).
 * The account is always addressed by ConnectedAccountId — never by provider id.
 * Responses carry Qasedak-owned records only (availability states, never raw
 * provider DTOs). Never regenerated by design sync.
 */
import { request } from "./http";
import {
  normalizeFollowerHistory,
  normalizeOverview,
  type FollowerHistoryPoint,
  type InstagramOverview,
} from "../../features/instagram/insights";

export interface InsightsApi {
  getOverview(token: string, workspaceId: string, accountId: string): Promise<InstagramOverview>;
  getFollowerHistory(
    token: string,
    workspaceId: string,
    accountId: string,
    limit?: number,
  ): Promise<FollowerHistoryPoint[]>;
}

export function insightsApi(): InsightsApi {
  return {
    getOverview: async (token, workspaceId, accountId) => {
      const payload = await request<unknown>(
        `/api/v1/workspaces/${workspaceId}/instagram/connections/${accountId}/overview`,
        { bearerToken: token },
      );
      return normalizeOverview(payload);
    },
    getFollowerHistory: async (token, workspaceId, accountId, limit) => {
      const query = limit !== undefined ? `?limit=${limit}` : "";
      const payload = await request<unknown>(
        `/api/v1/workspaces/${workspaceId}/instagram/connections/${accountId}/followers/history${query}`,
        { bearerToken: token },
      );
      return normalizeFollowerHistory(payload);
    },
  };
}