/*
 * Application-owned API client for the workspace Instagram media catalog
 * (GET /api/v1/workspaces/{id}/instagram/connections/{accountId}/media).
 * The account is always addressed by ConnectedAccountId — never by provider id.
 * Never regenerated by design sync.
 */
import { request } from "./http";
import { normalizePage, type MediaPickerPage } from "../../features/instagram/media";

export interface MediaListParams {
  limit?: number;
  cursor?: string | null;
}

export interface MediaApi {
  listMedia(
    token: string,
    workspaceId: string,
    accountId: string,
    params?: MediaListParams,
  ): Promise<MediaPickerPage>;
}

export function mediaApi(): MediaApi {
  return {
    listMedia: async (token, workspaceId, accountId, params = {}) => {
      const query = new URLSearchParams();
      if (params.limit !== undefined) query.set("limit", String(params.limit));
      if (params.cursor) query.set("cursor", params.cursor);
      const qs = query.toString();
      const url =
        `/api/v1/workspaces/${workspaceId}/instagram/connections/${accountId}/media` +
        (qs ? `?${qs}` : "");
      const payload = await request<unknown>(url, { bearerToken: token });
      return normalizePage(payload);
    },
  };
}