// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qasedak.Modules.Instagram.Infrastructure.Persistence;

#nullable disable

namespace Qasedak.Modules.Instagram.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InstagramDbContext))]
    [Migration("20260907012837_AddRevealFlows")]
    partial class AddRevealFlows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("instagram")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qasedak.Modules.Instagram.Domain.Accounts.ConnectedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisconnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("HealthDetail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LastSubscriptionCheckUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastTokenIssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Path")
                        .HasColumnType("integer");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("ProfileUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SubscriptionDetail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SubscriptionHealth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset?>("TokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderUserId")
                        .HasDatabaseName("IX_connected_accounts_active_routing_identity")
                        .HasFilter("\"DisconnectedAtUtc\" IS NULL");

                    b.HasIndex("WorkspaceId", "ProviderUserId")
                        .IsUnique()
                        .HasFilter("\"DisconnectedAtUtc\" IS NULL");

                    b.ToTable("connected_accounts", "instagram");
                });

            modelBuilder.Entity("Qasedak.Modules.Instagram.Infrastructure.Effects.CommentEffectRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConnectedAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EffectType")
                        .HasColumnType("integer");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerOperationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderCommentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderRecipientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAccountId", "ProviderCommentId", "EffectType")
                        .IsUnique();

                    b.ToTable("comment_effects", "instagram");
                });

            modelBuilder.Entity("Qasedak.Modules.Instagram.Infrastructure.Persistence.FollowerSnapshotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectedAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FollowerCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provenance")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SnapshotDateUtc")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAccountId", "SnapshotDateUtc")
                        .IsUnique();

                    b.ToTable("follower_snapshots", "instagram");
                });

            modelBuilder.Entity("Qasedak.Modules.Instagram.Infrastructure.Persistence.OAuthStateRow", b =>
                {
                    b.Property<string>("StateHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("StateHash");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("StateHash")
                        .IsUnique();

                    b.ToTable("oauth_states", "instagram");
                });

            modelBuilder.Entity("Qasedak.Modules.Instagram.Infrastructure.Persistence.RevealFlowRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ActionIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AutomationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AutomationVersionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConnectedAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CorrelationTokenPurpose")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FollowButtonTitle")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FollowGateMode")
                        .HasColumnType("integer");

                    b.Property<string>("FollowUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("GatePromptAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatePromptFailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("GatePromptProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("GatePromptStatus")
                        .HasColumnType("integer");

                    b.Property<string>("GatePromptText")
                        .IsRequired()
                        .HasMaxLength(640)
                        .HasColumnType("character varying(640)");

                    b.Property<bool>("IsLiveComment")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastFollowCheckAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastFollowState")
                        .HasColumnType("integer");

                    b.Property<int?>("LastFollowUnavailableReason")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastUserMessageAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NotificationOccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpeningPrivateReplyMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OpeningPrivateReplyRecipientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OpeningPrivateReplyText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ParticipantIGSID")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PostbackButtonTitle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProviderCommentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("RevealAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevealCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevealFailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RevealProviderMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RevealStatus")
                        .HasColumnType("integer");

                    b.Property<string>("RevealText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TriggerEventId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationTokenHash")
                        .IsUnique();

                    b.HasIndex("OpeningPrivateReplyMessageId");

                    b.HasIndex("ConnectedAccountId", "ProviderCommentId")
                        .IsUnique();

                    b.HasIndex("ConnectedAccountId", "ParticipantIGSID", "State");

                    b.ToTable("reveal_flows", "instagram");
                });

            modelBuilder.Entity("Qasedak.Modules.Instagram.Infrastructure.Persistence.StoredAccountToken", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ciphertext")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("AccountId");

                    b.ToTable("account_tokens", "instagram");
                });

            modelBuilder.Entity("Qasedak.Modules.Instagram.Infrastructure.Persistence.WebhookInboxEntry", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EventId");

                    b.HasIndex("Status", "ReceivedAtUtc");

                    b.ToTable("webhook_inbox", "instagram");
                });
#pragma warning restore 612, 618
        }
    }
}
