<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="..\..\Modules\Instagram\Qasedak.Modules.Instagram.Application\Qasedak.Modules.Instagram.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Instagram\Qasedak.Modules.Instagram.Domain\Qasedak.Modules.Instagram.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Instagram\Qasedak.Modules.Instagram.Infrastructure\Qasedak.Modules.Instagram.Infrastructure.csproj" />
  </ItemGroup>
</Project>
