// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qasedak.Modules.Contacts.Infrastructure.Persistence;

#nullable disable

namespace Qasedak.Modules.Contacts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    partial class ContactsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contacts")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactIdentityRow", b =>
                {
                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderIdentity")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("ContactId", "Channel", "ProviderIdentity");

                    b.HasIndex("WorkspaceId", "Channel", "ProviderIdentity")
                        .IsUnique();

                    b.ToTable("contact_identities", "contacts");
                });

            modelBuilder.Entity("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactInteractionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "OccurredAtUtc");

                    b.ToTable("contact_interactions", "contacts");
                });

            modelBuilder.Entity("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactNoteRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("WorkspaceId", "CreatedAtUtc");

                    b.ToTable("contact_notes", "contacts");
                });

            modelBuilder.Entity("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InteractionCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MergedIntoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Status", "LastSeenAtUtc");

                    b.ToTable("contacts", "contacts");
                });

            modelBuilder.Entity("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactTagRow", b =>
                {
                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("ContactId", "Tag");

                    b.HasIndex("WorkspaceId", "Tag");

                    b.ToTable("contact_tags", "contacts");
                });

            modelBuilder.Entity("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactIdentityRow", b =>
                {
                    b.HasOne("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactRow", null)
                        .WithMany("Identities")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactNoteRow", b =>
                {
                    b.HasOne("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactRow", null)
                        .WithMany("Notes")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactTagRow", b =>
                {
                    b.HasOne("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactRow", null)
                        .WithMany("Tags")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Qasedak.Modules.Contacts.Infrastructure.Persistence.ContactRow", b =>
                {
                    b.Navigation("Identities");

                    b.Navigation("Notes");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
