<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Qasedak.Modules.Billing.Application\Qasedak.Modules.Billing.Application.csproj" />
    <ProjectReference Include="..\Qasedak.Modules.Billing.Domain\Qasedak.Modules.Billing.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Qasedak.BuildingBlocks.Infrastructure\Qasedak.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
</Project>
